# permissions for end users to view gaia.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: gaia-viewer-role
rules:
- apiGroups:
  - gaia.my.domain
  resources:
  - gaia
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - gaia.my.domain
  resources:
  - gaia/status
  verbs:
  - get
